// Generated from src/content/docs/*.md by scripts/generate-docs.ts.
// Markdoc renderable trees. Server-only: see the note in scripts/generate-docs.ts.
import type { RenderableTreeNode } from "@markdoc/markdoc"

export const GENERATED_DOC_CONTENT: Record<string, RenderableTreeNode[]> = {
  "android-distribution": [
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "SproutOS distributes Android apps directly from the website. It does not publish Google Play",
        " ",
        "tracks. A project uploads one raw unsigned APK; the on-premises signer produces the installable APK",
        " ",
        "without exposing the app signing private key to a developer machine, GitHub Actions, or the control",
        " ",
        "plane.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "keep-the-application-identity-stable",
      },
      children: ["Keep the application identity stable"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Choose the Android application id before the first production release and do not change it. Every",
        " ",
        "update must use the same application id and signing identity, and its Android ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["versionCode"],
        },
        " must be",
        " ",
        "greater than the installed release.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The SproutOS Android client uses ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["com.sproutos.store"],
        },
        ". A different id is a different app to Android,",
        " ",
        "so it cannot update an existing installation in place.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Build a release APK that is deliberately unsigned. Do not upload an Android App Bundle (",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: [".aab"],
        },
        "), a",
        " ",
        "ZIP containing an APK, or an APK already signed by a developer key. The CLI validates this boundary",
        " ",
        "before uploading.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "establish-protected-signing-custody",
      },
      children: ["Establish protected signing custody"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: ["An authorized project owner runs the Android setup command once:"],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: ["sprout android setup my-android-app\nsprout android status my-android-app\n"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Setup creates or imports the project's signing identity through the protected signer. Treat this as",
        " ",
        "a custody operation: back up any permitted recovery material according to your organization policy,",
        " ",
        "restrict who can rotate it, and never commit keystores, passwords, or exported private keys.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Setup and signing do not register the application with Google. A SproutOS operator adds the exact",
        " ",
        "application id and public certificate fingerprint to the existing Play Console organization using",
        " ",
        "its manual ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["Add key"],
        },
        " flow. The signer has no Google credential and never exposes the private key.",
        " ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["sprout android status"],
        },
        " shows the public fingerprint and registration state. A signed release stays",
        " ",
        "hidden until Google's independent Android Developer ID Status API reports ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["REGISTERED"],
        },
        " for that",
        " ",
        "exact application id and fingerprint.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "A new package normally needs only that fingerprint. If Play asks for an ownership APK containing",
        " ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["assets/adi-registration.properties"],
        },
        " for an existing package or additional key, stop and contact",
        " ",
        "SproutOS operations for a future custody-safe workflow. Never export or regenerate the protected",
        " ",
        "key, substitute a debug key, or build the proof APK outside the signer custody boundary.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Before the first public release, record and independently compare the certificate fingerprint:",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: ["sprout android verify my-android-app --commit <40-character-source-commit>\n"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The verified source commit, application id, signing-certificate digest, version code, and artifact",
        " ",
        "digest form the release identity. A mismatch must fail closed; do not work around it by uninstalling",
        " ",
        "the existing app or accepting a new key.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "publish-from-github-actions",
      },
      children: ["Publish from GitHub Actions"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Build the unsigned APK, then pass the containing directory to the pinned Marketplace action:",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "yaml",
      },
      children: [
        'name: Publish Android app\non:\n  push:\n    tags: ["android-v*"]\n\npermissions:\n  contents: read\n  id-token: write\n\njobs:\n  publish:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v5\n      - uses: actions/setup-java@v4\n        with:\n          distribution: temurin\n          java-version: "21"\n      - uses: gradle/actions/setup-gradle@v4\n      - run: ./gradlew assembleRelease\n      - uses: MySproutOS/sproutos-deploy-action@0d5ce8bb74ecd598ae996c34d7d2cb5ac156a180\n        with:\n          preset: android\n          directory: app/build/outputs/apk/release\n          project: my-android-app\n          api-url: https://api.sproutos.me\n',
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The directory must contain exactly one APK. The action authenticates with GitHub OIDC and passes a",
        " ",
        "short-lived, repository-bound token to the CLI; do not add a long-lived SproutOS secret. The same",
        " ",
        "artifact can be deployed locally with:",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: [
        "sprout deploy my-android-app --preset android \\\n  --path app/build/outputs/apk/release/app-release-unsigned.apk \\\n  --version-code 42\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "test-installation-and-updating",
      },
      children: ["Test installation and updating"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Test the public user journey on a supported Android device or emulator before announcing a release:",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "ol",
      attributes: {},
      children: [
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: ["Open the SproutOS Android client and authenticate."],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "Find the listing and check its title, summary, icon, screenshots, release version, download size,",
            " ",
            "permissions, privacy/support links, and update notes.",
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "Install it from the website-backed catalogue and launch the installed application.",
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "Publish a higher ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["versionCode"],
            },
            ", return to the listing, install the update, and confirm Android",
            " ",
            "updates in place without changing the application id or losing app data.",
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "Compare the installed certificate digest and artifact digest with the release record, then verify",
            " ",
            "failed or superseded releases cannot be downloaded as current.",
          ],
        },
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Exercise this flow with Mobile MCP in automated acceptance so tests interact with the same visible",
        " ",
        "screens a user does. Shell-only APK installation can diagnose a build, but it does not prove",
        " ",
        "authentication, catalogue discovery, listing content, download authorization, installer handoff,",
        " ",
        "launch, or update behavior.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "If Android blocks the install, enable permission for the browser or SproutOS client to install",
        " ",
        "unknown apps and retry. Do not disable Android package verification. If an update reports a signing",
        " ",
        "conflict, stop: either the application id or protected signing identity changed.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "prepare-useful-listing-content",
      },
      children: ["Prepare useful listing content"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "A launch-ready listing needs more than an APK. Provide a concise name and summary, an accurate full",
        " ",
        "description, a high-resolution icon, phone screenshots from the actual release, support and privacy",
        " ",
        "URLs, release notes, and explicit content/permission disclosures. Describe what the app does and",
        " ",
        "what data leaves the device; do not make claims the release cannot demonstrate.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Keep the listing tied to the same immutable source commit and artifact digest shown by release",
        " ",
        "verification. Test every link and screenshot at phone width, and repeat the full install/update",
        " ",
        "journey after changing signing, download authorization, catalogue metadata, or Android client code.",
      ],
    },
  ],
  "background-workers": [
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "how-work-starts",
      },
      children: ["How work starts"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "SproutOS invokes your application when a queue has work. Handle the ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["queue.drain"],
        },
        " event, process the supplied batch, and return. The same deployed function can serve HTTP and workflow invocations.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "return-when-work-is-done",
      },
      children: ["Return when work is done"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Compute is billed in GB-seconds until the handler returns. Close database connections and do not leave a Redis subscribe, blocking read, timer, or worker loop alive. SproutOS invokes the function again when more work arrives.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Use a workflow step for work that must continue later. Split work that cannot finish within one invocation, enqueue the remainder, and return.",
      ],
    },
  ],
  billing: [
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "usage-and-credit",
      },
      children: ["Usage and credit"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Usage is recorded in an append-only ledger and grouped by service. Line items retain sub-cent precision; spendable credit is displayed in cents. SproutOS is prepaid: new work is refused once spendable credit is exhausted, delayed usage is capped at the available credit when posted, and provider-backed work cannot settle past the credit available after its reservation is released.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "queue-residency",
      },
      children: ["Queue residency"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Queue residency is queued payload bytes multiplied by how long they remain queued. It is storage over time, not a count of jobs and not ordinary cache usage.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "object-storage",
      },
      children: ["Object storage"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Mutable object storage records write and list requests, read requests, bytes delivered outside AWS, and stored byte-time. Deletes are free. These dimensions have no SproutOS markup.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Spendable credit includes a protected reserve for 48 hours of the latest measured object-storage bytes. When credit reaches that floor, new service requests stop while the funded retention window preserves the stored data. Adding credit clears the cutoff.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "platform-fees",
      },
      children: ["Platform fees"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Dimensions without an item-specific override use the standard 12% platform fee. Postgres compute has a 2% fee. Postgres storage, sandbox resources and egress, platform-funded AI, and operational agent duration use 0%; user-funded AI is recorded as externally charged rather than billed again. Payment processing is passed through separately.",
      ],
    },
  ],
  cli: [
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["sprout"],
        },
        " CLI is the command-line client for SproutOS. It uses the same project and deployment",
        " ",
        "contract as the dashboard and the GitHub Action.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "sign-in-and-choose-an-organization",
      },
      children: ["Sign in and choose an organization"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: ["Install a checksummed binary from the SproutOS GitHub release, then sign in:"],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: ["sprout auth login\nsprout org list\nsprout org use my-team\n"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Browser login uses PKCE. The resulting credential is stored in your operating system credential",
        " ",
        "store, not a plaintext configuration file. For a trusted headless environment, use",
        " ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["SPROUTOS_TOKEN"],
        },
        "; never put that value in a repository or command-line argument.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Add ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--json"],
        },
        " to get one stable JSON document for scripts and coding agents. Destructive commands",
        " ",
        "require an interactive confirmation, or ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--yes"],
        },
        "; JSON mode never prompts.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "create-a-project-in-an-available-region",
      },
      children: ["Create a project in an available region"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "A region is required when a project is created. Ask the active control plane for the current list,",
        " ",
        "then pass one of its exact codes:",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: [
        "sprout region list\nsprout project create --name my-site --region us-east-1 --blank\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Do not copy a region from an old example without checking ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["region list"],
        },
        ": availability is a",
        " ",
        "control-plane decision. A blank project is private or public according to the server default unless",
        " ",
        "you pass ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--private"],
        },
        " or ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--public"],
        },
        ".",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: ["You can also attach an existing repository:"],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: [
        "sprout project create --name my-site --region us-east-1 \\\n  --repository-id 01900000-0000-7000-8000-000000000000\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "For a repository GitHub cannot identify as a fork, add ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--upstream owner/repository"],
        },
        ". Root",
        " ",
        "directory and Dockerfile overrides are optional. Leaving them out preserves the source or signed",
        " ",
        "App Store listing defaults.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "install-from-the-app-store",
      },
      children: ["Install from the App Store"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: ["Copy a listing id from the SproutOS App Store and create its project:"],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: [
        "sprout project create --name analytics --region us-east-1 \\\n  --store 01900000-0000-7000-8000-000000000000 \\\n  --owner my-github-account --repository-name analytics\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The platform resolves an exact signed catalogue commit and immutable plugin digest. It creates the",
        " ",
        "destination repository and services; it does not execute instructions discovered in the upstream",
        " ",
        "repository.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Some listings declare setup inputs. Download or create a JSON array matching the fields shown by",
        " ",
        "the listing, then pass its file:",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "json",
      },
      children: [
        '[\n  { "key": "databasePassword", "value": "replace-me", "secret": true },\n  { "key": "port", "value": 3000, "secret": false }\n]\n',
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: [
        "sprout project create --name analytics --region us-east-1 \\\n  --store 01900000-0000-7000-8000-000000000000 \\\n  --template-input-file ./template-inputs.json\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Use ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--template-input-file -"],
        },
        " to read the array from stdin. This keeps secret values out of shell",
        " ",
        "history and the process list. Inputs cannot override the signed template's declared structure.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "configure-and-deploy",
      },
      children: ["Configure and deploy"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: ["Use environment and service commands after the project exists:"],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: [
        "sprout env set my-site DATABASE_URL --stdin\nsprout service list --project my-site\nsprout deploy my-site --preset next --path .next/standalone\nsprout deployment list --project my-site\nsprout logs my-site\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The CLI packages output deterministically, negotiates the upload, creates a release, and waits for",
        " ",
        "a terminal deployment result. The ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["static"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["web"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["next"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["hono"],
        },
        ", and ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["android"],
        },
        " presets share this",
        " ",
        "release path. Production database migrations remain a customer-owned GitHub Actions step; see",
        " ",
        {
          $$mdtype: "Tag",
          name: "DocLink",
          attributes: {
            href: "/docs/database-migrations",
          },
          children: ["Run database migrations"],
        },
        ".",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "manage-updates-and-groups",
      },
      children: ["Manage updates and groups"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "App Store and upstream-backed projects can ask SproutOS to open reviewed update pull requests:",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: [
        "sprout project update analytics --auto-update \\\n  --auto-update-cadence one_month --auto-update-mode suggest\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Use ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--auto-update-mode auto_merge"],
        },
        " only when reviewed pull requests should merge automatically",
        " ",
        "after all platform and repository checks pass. A logical group can be created with ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--group"],
        },
        "; add a",
        " ",
        "child using ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--parent-project <group-id>"],
        },
        " and select its customer-facing project with",
        " ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--primary-child <child-id>"],
        },
        " on the group.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Run ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["sprout --help"],
        },
        " or ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["sprout <command> --help"],
        },
        " for the complete current flag set. The major command",
        " ",
        "groups are ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["auth"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["org"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["region"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["project"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["env"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["service"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["deploy"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["deployment"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["logs"],
        },
        ",",
        " ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["android"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["api"],
        },
        ", and ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["template"],
        },
        ".",
      ],
    },
  ],
  connecting: [
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "tenant-scoped-credentials",
      },
      children: ["Tenant-scoped credentials"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Provisioning or rotating Postgres, Valkey, or OpenSearch returns its connection URI once. Put it in the project's encrypted environment variables. SproutOS stores a verifier, not a recoverable copy, so those URIs cannot be revealed later.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Object storage is the exception. Its secret is derived rather than stored, so an authorized organization member can use ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["View credentials"],
        },
        " again. Rotation still revokes the old access immediately at the storage proxy. See ",
        {
          $$mdtype: "Tag",
          name: "DocLink",
          attributes: {
            href: "/docs/object-storage",
          },
          children: ["Use object storage"],
        },
        " for SDK configuration and supported operations.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "service-variables",
      },
      children: ["Service variables"],
    },
    {
      $$mdtype: "Tag",
      name: "ul",
      attributes: {},
      children: [
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "Postgres uses ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["DATABASE_URL"],
            },
            ".",
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "Valkey uses ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["VALKEY_URL"],
            },
            " or ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["REDIS_URL"],
            },
            "; BullMQ also uses the injected ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["BULLMQ_PREFIX"],
            },
            ".",
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "OpenSearch uses ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["ELASTICSEARCH_URL"],
            },
            " and automatically scopes index names.",
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "Object storage uses ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_ENDPOINT"],
            },
            ", ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_REGION"],
            },
            ", ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_BUCKET_NAME"],
            },
            ", ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_ACCESS_KEY_ID"],
            },
            ", ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_SECRET_ACCESS_KEY"],
            },
            ", and path-style addressing.",
          ],
        },
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "All endpoints pass through tenant-enforcing SproutOS proxies. Close connections before a function returns.",
      ],
    },
  ],
  "database-migrations": [
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "the-workflow-owns-production-migrations",
      },
      children: ["The workflow owns production migrations"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Your GitHub Actions workflow decides when production database migrations run. SproutOS does not",
        " ",
        "scan a repository, discover a migration command, or start a migration because application code was",
        " ",
        "deployed.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The recommended setup is a dedicated SproutOS ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["migrator project"],
        },
        ". Its GitHub Actions job uploads",
        " ",
        "the built migrator, waits for SproutOS to finish running it, and only then allows the application",
        " ",
        "projects that use that database to deploy. Give one project responsibility for each database. Do",
        " ",
        "not attach the same migration to several application projects and let them race.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "recommended-deploy-a-migrator-project-first",
      },
      children: ["Recommended: deploy a migrator project first"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Build the migrator separately from the request-serving application and pass it to the deploy action",
        " ",
        "with ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["migration-directory"],
        },
        ". The action waits for a terminal result, so GitHub's ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["needs"],
        },
        " dependency",
        " ",
        "is the gate between the schema and the applications:",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "yaml",
      },
      children: [
        "name: Migrate and deploy to SproutOS\non:\n  push:\n    branches: [main]\n\npermissions:\n  contents: read\n  id-token: write\n\njobs:\n  migrate:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v5\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n      - run: npm ci\n      - run: npm run build:migrator\n      - uses: MySproutOS/sproutos-deploy-action@0d5ce8bb74ecd598ae996c34d7d2cb5ac156a180\n        with:\n          preset: hono\n          directory: apps/migrator/dist\n          project: my-app-migrator\n          migration-directory: apps/migrator/dist\n          migration-handler: migrate.handler\n          api-url: https://api.sproutos.me\n\n  deploy-web:\n    needs: migrate\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v5\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n      - run: npm ci\n      - run: npm run build\n      - uses: MySproutOS/sproutos-deploy-action@0d5ce8bb74ecd598ae996c34d7d2cb5ac156a180\n        with:\n          preset: next\n          directory: apps/website/.next/standalone\n          project: my-app-web\n          api-url: https://api.sproutos.me\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Replace the commands, preset, directories, and handler with the repository's real build. The",
        " ",
        "migrator project is a deployable project, but it should not be the group's customer-facing primary",
        " ",
        "project.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Add ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["needs: migrate"],
        },
        " to every job that deploys code against the migrated database. When several",
        " ",
        "applications share one database, they may deploy in parallel after that one migration succeeds.",
        " ",
        "When applications use different databases, give each database its own migrator job and depend only",
        " ",
        "on the relevant one.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "SproutOS runs the uploaded migrator with that project's production environment, including its",
        " ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["DATABASE_URL"],
        },
        ", before publishing the migrator project's new version. A failed migration fails the",
        " ",
        "GitHub job and leaves dependent jobs unstarted. SproutOS does not retry a migration automatically:",
        " ",
        "after a failure, inspect whether it partially applied before starting another run.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "alternative-run-the-command-directly-in-ci",
      },
      children: ["Alternative: run the command directly in CI"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "You may run the repository's migration command directly on the GitHub runner instead. In that",
        " ",
        "model, GitHub needs a production database credential stored as an Actions secret; the OIDC token",
        " ",
        "used by the SproutOS deploy action is not a database credential.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "yaml",
      },
      children: [
        "jobs:\n  migrate:\n    runs-on: ubuntu-latest\n    env:\n      DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}\n    steps:\n      - uses: actions/checkout@v5\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n      - run: npm ci\n      - run: npm run migrate\n\n  deploy-web:\n    needs: migrate\n    # Build and deploy the application here.\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Use this pattern when the migration cannot run in the SproutOS migrator runtime or your existing CI",
        " ",
        "already owns database access. Never commit the connection URI or print it in workflow output.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "make-schema-changes-safe-for-several-projects",
      },
      children: ["Make schema changes safe for several projects"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The old application versions keep serving until their deployment jobs finish. Write migrations so",
        " ",
        "both old and new code can use the intermediate schema: add before removing, deploy readers before",
        " ",
        "dropping old columns, and move destructive cleanup into a later migration.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Do not run migrations during application startup. Several function instances may start at once,",
        " ",
        "which turns one schema change into concurrent migration attempts.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "If a project has no database or no migrations, say so in the workflow or repository instructions",
        " ",
        "rather than leaving ownership ambiguous.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "sandboxes-do-not-migrate-production",
      },
      children: ["Sandboxes do not migrate production"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "A SproutOS coding-agent sandbox starts without ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["DATABASE_URL"],
        },
        ". The agent can request a named,",
        " ",
        "disposable 24-hour branch of the project's database through its scoped sandbox action. Run",
        " ",
        "migrations against that isolated branch to verify the schema, seed data, and application together.",
        " ",
        "A successful sandbox migration does not replace the GitHub Actions migration job and does not prove",
        " ",
        "that production was migrated.",
      ],
    },
  ],
  "github-action": [
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "github-actions",
      },
      children: ["GitHub Actions"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Build the target, then call the Marketplace action. The reviewed action at commit",
        " ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["0d5ce8bb74ecd598ae996c34d7d2cb5ac156a180"],
        },
        " is a thin wrapper around the published ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["sprout"],
        },
        " CLI",
        " ",
        "v0.1.0. The current local CLI is v0.2.1; it adds the complete region-aware project, signed-template,",
        " ",
        "Android release, and resumable log-stream commands while preserving the action's packaging and",
        " ",
        "deployment protocol.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "yaml",
      },
      children: [
        "name: Deploy to SproutOS\non:\n  push:\n    branches: [main]\n\npermissions:\n  contents: read\n  id-token: write\n\njobs:\n  deploy:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v5\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 22\n      - run: npm ci\n      - run: npm run build\n      - uses: MySproutOS/sproutos-deploy-action@0d5ce8bb74ecd598ae996c34d7d2cb5ac156a180\n        with:\n          preset: next\n          directory: apps/website/.next/standalone\n          project: my-web-project\n          api-url: https://api.sproutos.me\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["id-token: write"],
        },
        " lets GitHub identify the repository to SproutOS without a stored deployment",
        " ",
        "secret. Do not add a long-lived SproutOS token to GitHub for this workflow. The platform verifies",
        " ",
        "the repository and workflow identity before issuing a short-lived deployment credential.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The action uploads build output; it does not decide how your application builds. Use ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["next"],
        },
        ",",
        " ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["hono"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["web"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["static"],
        },
        ", or ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["android"],
        },
        " as the preset and point ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["directory"],
        },
        " at the finished artifact. In a",
        " ",
        "monorepo, use one workflow step per deployable target and always name ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["project"],
        },
        ".",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Internally, the wrapper exchanges GitHub's OIDC assertion for a short-lived deployment token and",
        " ",
        "passes it to the pinned CLI through the environment, never a command-line argument. That token is",
        " ",
        "not a secret developers create or store.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The action waits for a terminal deployment state. A missing artifact or rejected repository",
        " ",
        "identity fails the GitHub job instead of reporting a successful upload.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Production migrations remain part of the customer's GitHub Actions workflow. Use a dedicated",
        " ",
        "migrator project and make application deploy jobs wait for it, or run the migration command directly",
        " ",
        "in CI. See ",
        {
          $$mdtype: "Tag",
          name: "DocLink",
          attributes: {
            href: "/docs/database-migrations",
          },
          children: ["Run database migrations"],
        },
        " for both patterns and their failure",
        " ",
        "boundaries.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "run-the-same-deployment-locally",
      },
      children: ["Run the same deployment locally"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Install ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["sprout"],
        },
        " from the checksummed binaries in the",
        " ",
        {
          $$mdtype: "Tag",
          name: "DocLink",
          attributes: {
            href: "https://github.com/MySproutOS/SproutOS/releases/tag/cli-v0.2.1",
          },
          children: ["SproutOS CLI v0.2.1 release"],
        },
        ", then",
        " ",
        "sign in and deploy:",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "shell",
      },
      children: [
        "sprout auth login\nsprout org use my-team\nsprout deploy my-web-project --preset next \\\n  --path apps/website/.next/standalone\n",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Browser login uses PKCE and stores the resulting credential in your operating system's credential",
        " ",
        "store. ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["SPROUTOS_TOKEN"],
        },
        " is the headless CI path; do not put it in a repository or pass it on a",
        " ",
        "command line that will be saved in shell history.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Every command also supports stable ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--json"],
        },
        " output for scripts and coding agents. Destructive",
        " ",
        "commands require confirmation or ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["--yes"],
        },
        ".",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The release contains macOS arm64 and x86-64, Linux arm64 and x86-64, and Windows x86-64 binaries,",
        " ",
        "plus ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["SHA256SUMS"],
        },
        " and ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["sprout-v0.2.1-manifest.json"],
        },
        ". Verify the selected archive against both files.",
        " ",
        "The action also verifies GitHub's artifact attestation and the release's exact source revision",
        " ",
        "before it executes the binary.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "give-a-local-coding-agent-the-sproutos-skill",
      },
      children: ["Give a local coding agent the SproutOS skill"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Download ",
        {
          $$mdtype: "Tag",
          name: "DocLink",
          attributes: {
            href: "/skills/sproutos/SKILL.md",
          },
          children: ["the public SproutOS skill"],
        },
        ". It teaches an agent the project,",
        " ",
        "service, environment, migration, template, and deployment boundaries without starting a paid",
        " ",
        "SproutOS sandbox.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "ul",
      attributes: {},
      children: [
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "Claude Code: save it as ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: [".claude/skills/sproutos/SKILL.md"],
            },
            " in the repository.",
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "Codex: save it as ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["~/.codex/skills/sproutos/SKILL.md"],
            },
            " for your account.",
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            "An ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["AGENTS.md"],
            },
            "-only harness: preserve the existing file and add a short instruction telling the",
            " ",
            "agent to read the downloaded ",
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["SKILL.md"],
            },
            "; do not replace repository instructions.",
          ],
        },
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "A local agent uses your computer and the model account configured in your harness. SproutOS does",
        " ",
        "not charge sandbox time or model usage for that work. Databases, deployments, storage, and other",
        " ",
        "SproutOS resources created by the agent are still metered normally.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The skill is instructions, not a credential. Authenticate the ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["sprout"],
        },
        " CLI yourself, or set",
        " ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["SPROUTOS_TOKEN"],
        },
        " only in a trusted headless environment.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "deployment-templates",
      },
      children: ["Deployment templates"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "App Store eligibility and deployment behavior come only from the signed",
        " ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["MySproutOS/Deployment-Templates"],
        },
        " catalogue. SproutOS verifies the catalogue provenance, exact",
        " ",
        "upstream commit, and immutable plugin digest before applying a recipe.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The reviewed template source at commit ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["c86dfdb7f055cb6cdf499b23f84ab91d640ca7a1"],
        },
        " generates the",
        " ",
        "canonical OIDC workflows for Umami and Memos. Those workflows pin the deploy action to the full",
        " ",
        "commit above; they do not follow a mutable action tag.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Generated forks may contain ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: [".config/sproutos.toml"],
        },
        ". It is declarative, contains no secret values,",
        " ",
        "and helps humans and agents understand the chosen services and bindings. It is not the catalogue",
        " ",
        "authority and cannot choose or replace executable template code.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Never discover deployment behavior from an instruction file in an arbitrary upstream repository.",
        " ",
        "Template plugins run without network, GitHub, SproutOS, or customer credentials; the control-plane",
        " ",
        "worker owns provisioning, commits, pushes, and deployment.",
      ],
    },
  ],
  limits: [
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "runtime",
      },
      children: ["Runtime"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "An invocation runs for at most 15 minutes. Split longer jobs and enqueue the remainder. Memory is configurable from 128 MB to 10 GB and CPU grows with memory.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "payloads-and-builds",
      },
      children: ["Payloads and builds"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Request and response bodies are limited to 6 MB; use object storage for larger data. The deploy tooling refuses application bundles over 200 MB uncompressed, ahead of Lambda's 250 MB hard limit.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "concurrency",
      },
      children: ["Concurrency"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Invocations may run concurrently in isolated environments. Pools created at module scope may be reused by a warm instance; never store a user's session or request state there.",
      ],
    },
  ],
  navigation: [
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "organizations-and-groups",
      },
      children: ["Organizations and groups"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "An organization owns billing and access. A ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["group"],
        },
        " is one GitHub repository. Its child projects are the deployable targets inside that repository, such as a web app and an API.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Open ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["Projects"],
        },
        " to see groups and their children. Group settings hold repository-wide choices such as upstream updates and the primary deployed project.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "projects-and-domains",
      },
      children: ["Projects and domains"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "A project is one deployable directory and branch. Its overview shows the live SproutOS hostname; ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["Domains"],
        },
        " adds a custom hostname. ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["Environment"],
        },
        " stores encrypted variables and ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["Observability"],
        },
        " shows requests, logs, and failures.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "databases-and-other-services",
      },
      children: ["Databases and other services"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Use ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["Databases"],
        },
        " for Postgres and the project service screens for Valkey, search, and object storage. Postgres, Valkey, and search credentials are shown once when created or rotated. Object-storage credentials can be viewed again because their secret is derived; rotation still revokes the previous credential.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "workflows-and-agents",
      },
      children: ["Workflows and agents"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Workflows attached to a repository appear inside its group. The global ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["Workflows"],
        },
        " page is for standalone automation repositories. Agent conversations and previews stay with the project they modify.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "billing-and-deletion",
      },
      children: ["Billing and deletion"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Billing groups measured usage by service and keeps an append-only credit ledger. Deleting a project tears down its resources but retains billing and audit history. GitHub repositories are retained unless you explicitly select them for deletion.",
      ],
    },
  ],
  "oauth-applications": [
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "register-and-redirect",
      },
      children: ["Register and redirect"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Register an OAuth client in SproutOS and add exact HTTPS redirect URIs. Public clients must use Authorization Code with PKCE (",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["S256"],
        },
        ") and must never ship a client secret.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Send users to the authorization endpoint with ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["client_id"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["redirect_uri"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["response_type=code"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["code_challenge"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["code_challenge_method=S256"],
        },
        ", ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["state"],
        },
        ", and the scopes you need. Validate ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["state"],
        },
        " before exchanging the returned code.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "ask-only-for-needed-access",
      },
      children: ["Ask only for needed access"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Database creation uses ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["database:create"],
        },
        " and spends the user's SproutOS credit. When the authorization request includes ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["intent=create_personal_database"],
        },
        ", consent explains the expected billing. The user may omit that optional permission and still sign in to your application. Pressing Cancel stops authorization.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "A grant may include database creation even when the account has no credit. The creation request itself returns HTTP 402 until credit is available.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "tokens-and-credentials",
      },
      children: ["Tokens and credentials"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Exchange the code with its original ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["code_verifier"],
        },
        ". Send access tokens as ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["Authorization: Bearer …"],
        },
        ". Refresh tokens are rotated; replace the stored refresh token after every successful refresh.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Database credentials belong to the OAuth grant that created them. Rotating an application credential does not rotate the user's credential or another application's credential. Connection URIs are returned once and cannot be revealed later.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "revocation",
      },
      children: ["Revocation"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Users can revoke your grant from settings. Revocation stops new API calls and revokes credentials owned by that grant. Resources the user chooses to keep remain theirs.",
      ],
    },
  ],
  "object-storage": [
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "mutable-storage-and-static-deployments",
      },
      children: ["Mutable storage and static deployments"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Object storage is mutable application data: uploads, photos, attachments, exports, and other files your application reads and changes while it runs. An ordinary S3 SDK talks to the SproutOS storage endpoint, which authenticates the project, confines every request to its bucket, and forwards it to S3.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "A static deployment is different. SproutOS expands an immutable build artifact and serves it through CloudFront. Customers do not receive credentials to edit that release in place; publish another deployment to change it.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "get-the-connection-values",
      },
      children: ["Get the connection values"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Open ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["Databases"],
        },
        ", find the object-storage service, and select ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["View credentials"],
        },
        ". The panel provides:",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "ul",
      attributes: {},
      children: [
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_ENDPOINT"],
            },
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_REGION"],
            },
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_BUCKET_NAME"],
            },
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_ACCESS_KEY_ID"],
            },
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_SECRET_ACCESS_KEY"],
            },
          ],
        },
        {
          $$mdtype: "Tag",
          name: "li",
          attributes: {},
          children: [
            {
              $$mdtype: "Tag",
              name: "code",
              attributes: {},
              children: ["S3_FORCE_PATH_STYLE=true"],
            },
          ],
        },
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The project receives the same values as encrypted environment variables when the service is attached. Object storage is the exception to the usual one-time credential rule: ",
        {
          $$mdtype: "Tag",
          name: "strong",
          attributes: {},
          children: ["View credentials"],
        },
        " can reconstruct its derived secret later. Keep it private. Rotating or deleting the credential revokes the old access at the SproutOS proxy; it is not an AWS credential and cannot be used against AWS directly.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "python-with-boto3",
      },
      children: ["Python with boto3"],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "python",
      },
      children: [
        'import os\n\nimport boto3\nfrom botocore.config import Config\n\ns3 = boto3.client(\n    "s3",\n    endpoint_url=os.environ["S3_ENDPOINT"],\n    region_name=os.environ["S3_REGION"],\n    aws_access_key_id=os.environ["S3_ACCESS_KEY_ID"],\n    aws_secret_access_key=os.environ["S3_SECRET_ACCESS_KEY"],\n    config=Config(s3={"addressing_style": "path"}),\n)\n\nbucket = os.environ["S3_BUCKET_NAME"]\ns3.put_object(Bucket=bucket, Key="photos/cat.jpg", Body=image_bytes)\nphoto = s3.get_object(Bucket=bucket, Key="photos/cat.jpg")["Body"].read()\n',
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Do not set an AWS session token. Always pass the displayed endpoint and use path-style addressing; the bucket must remain in the URL path rather than the hostname.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "typescript-with-the-aws-sdk",
      },
      children: ["TypeScript with the AWS SDK"],
    },
    {
      $$mdtype: "Tag",
      name: "CodeBlock",
      attributes: {
        language: "typescript",
      },
      children: [
        'import { GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3"\n\nconst s3 = new S3Client({\n  endpoint: process.env.S3_ENDPOINT,\n  region: process.env.S3_REGION,\n  credentials: {\n    accessKeyId: process.env.S3_ACCESS_KEY_ID!,\n    secretAccessKey: process.env.S3_SECRET_ACCESS_KEY!,\n  },\n  forcePathStyle: true,\n})\n\nconst Bucket = process.env.S3_BUCKET_NAME!\nawait s3.send(new PutObjectCommand({ Bucket, Key: "exports/report.json", Body: report }))\nconst stored = await s3.send(new GetObjectCommand({ Bucket, Key: "exports/report.json" }))\n',
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "supported-operations-and-limits",
      },
      children: ["Supported operations and limits"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Object reads, writes, heads, deletes, listings, and ordinary SDK multipart uploads are supported. Multipart upload is the right choice when one upload request would exceed the service's per-request body limit.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Presigned URLs, virtual-host bucket addressing, SigV4 streaming-chunked uploads, server-side ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["CopyObject"],
        },
        ", and conditional or range reads are not supported. Download the source and upload a new object instead of using ",
        {
          $$mdtype: "Tag",
          name: "code",
          attributes: {},
          children: ["CopyObject"],
        },
        "; download a whole object rather than depending on a byte range. A presigned URL would let a request outlive the live credential check, virtual-host addressing would move the tenant decision into customer-controlled DNS, and streaming-chunked SigV4 requires verification of every signed frame.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The proxy spools an upload to bounded disk while verifying its payload signature, then streams it to S3. Downloads stream with backpressure rather than being loaded into application memory.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "Heading",
      attributes: {
        level: 2,
        id: "metering-and-credit-cutoff",
      },
      children: ["Metering and credit cutoff"],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "Object storage meters write and list requests, read requests, bytes delivered outside AWS, and stored byte-time. Deletes are not charged. SproutOS adds no platform markup to these dimensions.",
      ],
    },
    {
      $$mdtype: "Tag",
      name: "p",
      attributes: {},
      children: [
        "The billing system protects enough spendable credit for 48 hours of the latest measured stored bytes. When the remaining credit reaches that reserve, new storage requests are refused while the already-funded retention window keeps the data. Add credit before retrying a refused request.",
      ],
    },
  ],
}
