// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
  GetAdminUsersData,
  GetAdminUsersResponses,
  PostAdminUsersImpersonateData,
  PostAdminUsersImpersonateErrors,
  PostAdminUsersImpersonateResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta
}

/**
 * Find a user across every organization
 */
export const getAdminUsers = <ThrowOnError extends boolean = false>(
  options?: Options<GetAdminUsersData, ThrowOnError>,
): RequestResult<GetAdminUsersResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetAdminUsersResponses, unknown, ThrowOnError>({
    url: "/admin/users",
    ...options,
  })

/**
 * Sign in as a user, for support. Recorded against both people.
 */
export const postAdminUsersImpersonate = <ThrowOnError extends boolean = false>(
  options?: Options<PostAdminUsersImpersonateData, ThrowOnError>,
): RequestResult<
  PostAdminUsersImpersonateResponses,
  PostAdminUsersImpersonateErrors,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    PostAdminUsersImpersonateResponses,
    PostAdminUsersImpersonateErrors,
    ThrowOnError
  >({
    url: "/admin/users/impersonate",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
