// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetAdminManagedDomainPoliciesByPolicyIdResponse,
  GetAdminManagedDomainPoliciesResponse,
  GetAdminUsersResponse,
  PatchAdminManagedDomainPoliciesByPolicyIdResponse,
  PostAdminManagedDomainPoliciesResponse,
  PostAdminUsersImpersonateResponse,
} from "./types.gen"

export const getAdminManagedDomainPoliciesResponseTransformer = async (
  data: any,
): Promise<GetAdminManagedDomainPoliciesResponse> => {
  data.data = data.data.map((item: any) => {
    item.createdAt = new Date(item.createdAt)
    item.updatedAt = new Date(item.updatedAt)
    if (item.disabledAt) {
      item.disabledAt = new Date(item.disabledAt)
    }
    return item
  })
  return data
}

export const postAdminManagedDomainPoliciesResponseTransformer = async (
  data: any,
): Promise<PostAdminManagedDomainPoliciesResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.disabledAt) {
    data.disabledAt = new Date(data.disabledAt)
  }
  return data
}

export const getAdminManagedDomainPoliciesByPolicyIdResponseTransformer = async (
  data: any,
): Promise<GetAdminManagedDomainPoliciesByPolicyIdResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.disabledAt) {
    data.disabledAt = new Date(data.disabledAt)
  }
  return data
}

export const patchAdminManagedDomainPoliciesByPolicyIdResponseTransformer = async (
  data: any,
): Promise<PatchAdminManagedDomainPoliciesByPolicyIdResponse> => {
  data.createdAt = new Date(data.createdAt)
  data.updatedAt = new Date(data.updatedAt)
  if (data.disabledAt) {
    data.disabledAt = new Date(data.disabledAt)
  }
  return data
}

export const getAdminUsersResponseTransformer = async (
  data: any,
): Promise<GetAdminUsersResponse> => {
  data.items = data.items.map((item: any) => {
    if (item.deletedAt) {
      item.deletedAt = new Date(item.deletedAt)
    }
    item.createdAt = new Date(item.createdAt)
    return item
  })
  return data
}

export const postAdminUsersImpersonateResponseTransformer = async (
  data: any,
): Promise<PostAdminUsersImpersonateResponse> => {
  data.expiresAt = new Date(data.expiresAt)
  return data
}
