// This file is auto-generated by @hey-api/openapi-ts

import type { GetAdminUsersResponse, PostAdminUsersImpersonateResponse } from "./types.gen"

export const getAdminUsersResponseTransformer = async (
  data: any,
): Promise<GetAdminUsersResponse> => {
  data.items = data.items.map((item: any) => {
    if (item.deletedAt) {
      item.deletedAt = new Date(item.deletedAt)
    }
    item.createdAt = new Date(item.createdAt)
    return item
  })
  return data
}

export const postAdminUsersImpersonateResponseTransformer = async (
  data: any,
): Promise<PostAdminUsersImpersonateResponse> => {
  data.expiresAt = new Date(data.expiresAt)
  return data
}
