// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3001" | (string & {})
}

export type InnerErrorT = {
  code: string
  innererror?: InnerErrorT
}

export type ErrorObjectT = {
  code:
    | "BadRequest"
    | "Unauthenticated"
    | "Unauthorized"
    | "Forbidden"
    | "NotFound"
    | "MethodNotAllowed"
    | "Conflict"
    | "UnprocessableEntity"
    | "TooManyRequests"
    | "InternalServerError"
    | "ServiceUnavailable"
    | "InsufficientPermissions"
    | "ValidationFailed"
    | "InvalidInput"
    | "MissingRequiredField"
    | "ResourceNotFound"
    | "ResourceAlreadyExists"
    | "ResourceLocked"
    | "OperationFailed"
    | "DataIntegrityViolation"
    | "RateLimitExceeded"
    | string
  message: string
  target?: string
  details?: Array<ErrorObjectT>
  innererror?: InnerErrorT
}

export type ErrorResponseT = {
  error: ErrorObjectT
}

export type GetAdminUsersData = {
  body?: never
  path?: never
  query?: {
    q?: string
    limit?: number
    cursor?: string
  }
  url: "/admin/users"
}

export type GetAdminUsersResponses = {
  /**
   * Users
   */
  200: {
    items: Array<{
      id: string
      email: string
      name: string | null
      githubLogin: string | null
      isAdmin: boolean
      deletedAt: Date | null
      organizationCount: number
      createdAt: Date
    }>
    nextCursor: string | null
  }
}

export type GetAdminUsersResponse = GetAdminUsersResponses[keyof GetAdminUsersResponses]

export type PostAdminUsersImpersonateData = {
  body?: {
    userId: string
    reason: string
  }
  path?: never
  query?: never
  url: "/admin/users/impersonate"
}

export type PostAdminUsersImpersonateErrors = {
  /**
   * The target cannot be impersonated
   */
  400: ErrorResponseT
  /**
   * No such user
   */
  404: ErrorResponseT
}

export type PostAdminUsersImpersonateError =
  PostAdminUsersImpersonateErrors[keyof PostAdminUsersImpersonateErrors]

export type PostAdminUsersImpersonateResponses = {
  /**
   * The session cookie is now the target user's
   */
  200: {
    userId: string
    email: string
    expiresAt: Date
  }
}

export type PostAdminUsersImpersonateResponse =
  PostAdminUsersImpersonateResponses[keyof PostAdminUsersImpersonateResponses]
