// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from "@tanstack/react-query"

import { client } from "../client.gen"
import {
  deleteAdminManagedDomainPoliciesByPolicyId,
  getAdminManagedDomainPolicies,
  getAdminManagedDomainPoliciesByPolicyId,
  getAdminUsers,
  type Options,
  patchAdminManagedDomainPoliciesByPolicyId,
  postAdminManagedDomainPolicies,
  postAdminStoreListingsByListingIdAndroidRelease,
  postAdminUsersImpersonate,
} from "../sdk.gen"
import type {
  DeleteAdminManagedDomainPoliciesByPolicyIdData,
  DeleteAdminManagedDomainPoliciesByPolicyIdError,
  DeleteAdminManagedDomainPoliciesByPolicyIdResponse,
  GetAdminManagedDomainPoliciesByPolicyIdData,
  GetAdminManagedDomainPoliciesByPolicyIdError,
  GetAdminManagedDomainPoliciesByPolicyIdResponse,
  GetAdminManagedDomainPoliciesData,
  GetAdminManagedDomainPoliciesResponse,
  GetAdminUsersData,
  GetAdminUsersResponse,
  PatchAdminManagedDomainPoliciesByPolicyIdData,
  PatchAdminManagedDomainPoliciesByPolicyIdError,
  PatchAdminManagedDomainPoliciesByPolicyIdResponse,
  PostAdminManagedDomainPoliciesData,
  PostAdminManagedDomainPoliciesError,
  PostAdminManagedDomainPoliciesResponse,
  PostAdminStoreListingsByListingIdAndroidReleaseData,
  PostAdminStoreListingsByListingIdAndroidReleaseError,
  PostAdminStoreListingsByListingIdAndroidReleaseResponse,
  PostAdminUsersImpersonateData,
  PostAdminUsersImpersonateError,
  PostAdminUsersImpersonateResponse,
} from "../types.gen"

/**
 * Selects the exact signed Android release published by a global listing
 */
export const postAdminStoreListingsByListingIdAndroidReleaseMutation = (
  options?: Partial<Options<PostAdminStoreListingsByListingIdAndroidReleaseData>>,
): UseMutationOptions<
  PostAdminStoreListingsByListingIdAndroidReleaseResponse,
  PostAdminStoreListingsByListingIdAndroidReleaseError,
  Options<PostAdminStoreListingsByListingIdAndroidReleaseData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAdminStoreListingsByListingIdAndroidReleaseResponse,
    PostAdminStoreListingsByListingIdAndroidReleaseError,
    Options<PostAdminStoreListingsByListingIdAndroidReleaseData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAdminStoreListingsByListingIdAndroidRelease({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getAdminManagedDomainPoliciesQueryKey = (
  options?: Options<GetAdminManagedDomainPoliciesData>,
) => createQueryKey("getAdminManagedDomainPolicies", options)

/**
 * Lists managed custom-domain policies
 */
export const getAdminManagedDomainPoliciesOptions = (
  options?: Options<GetAdminManagedDomainPoliciesData>,
) =>
  queryOptions<
    GetAdminManagedDomainPoliciesResponse,
    DefaultError,
    GetAdminManagedDomainPoliciesResponse,
    ReturnType<typeof getAdminManagedDomainPoliciesQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAdminManagedDomainPolicies({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getAdminManagedDomainPoliciesQueryKey(options),
  })

/**
 * Creates an organization-bound managed domain suffix
 */
export const postAdminManagedDomainPoliciesMutation = (
  options?: Partial<Options<PostAdminManagedDomainPoliciesData>>,
): UseMutationOptions<
  PostAdminManagedDomainPoliciesResponse,
  PostAdminManagedDomainPoliciesError,
  Options<PostAdminManagedDomainPoliciesData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAdminManagedDomainPoliciesResponse,
    PostAdminManagedDomainPoliciesError,
    Options<PostAdminManagedDomainPoliciesData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAdminManagedDomainPolicies({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Soft-deletes a managed policy and tears down attached domains
 */
export const deleteAdminManagedDomainPoliciesByPolicyIdMutation = (
  options?: Partial<Options<DeleteAdminManagedDomainPoliciesByPolicyIdData>>,
): UseMutationOptions<
  DeleteAdminManagedDomainPoliciesByPolicyIdResponse,
  DeleteAdminManagedDomainPoliciesByPolicyIdError,
  Options<DeleteAdminManagedDomainPoliciesByPolicyIdData>
> => {
  const mutationOptions: UseMutationOptions<
    DeleteAdminManagedDomainPoliciesByPolicyIdResponse,
    DeleteAdminManagedDomainPoliciesByPolicyIdError,
    Options<DeleteAdminManagedDomainPoliciesByPolicyIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await deleteAdminManagedDomainPoliciesByPolicyId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getAdminManagedDomainPoliciesByPolicyIdQueryKey = (
  options: Options<GetAdminManagedDomainPoliciesByPolicyIdData>,
) => createQueryKey("getAdminManagedDomainPoliciesByPolicyId", options)

/**
 * Gets one managed custom-domain policy
 */
export const getAdminManagedDomainPoliciesByPolicyIdOptions = (
  options: Options<GetAdminManagedDomainPoliciesByPolicyIdData>,
) =>
  queryOptions<
    GetAdminManagedDomainPoliciesByPolicyIdResponse,
    GetAdminManagedDomainPoliciesByPolicyIdError,
    GetAdminManagedDomainPoliciesByPolicyIdResponse,
    ReturnType<typeof getAdminManagedDomainPoliciesByPolicyIdQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAdminManagedDomainPoliciesByPolicyId({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getAdminManagedDomainPoliciesByPolicyIdQueryKey(options),
  })

/**
 * Updates or disables a managed domain policy
 */
export const patchAdminManagedDomainPoliciesByPolicyIdMutation = (
  options?: Partial<Options<PatchAdminManagedDomainPoliciesByPolicyIdData>>,
): UseMutationOptions<
  PatchAdminManagedDomainPoliciesByPolicyIdResponse,
  PatchAdminManagedDomainPoliciesByPolicyIdError,
  Options<PatchAdminManagedDomainPoliciesByPolicyIdData>
> => {
  const mutationOptions: UseMutationOptions<
    PatchAdminManagedDomainPoliciesByPolicyIdResponse,
    PatchAdminManagedDomainPoliciesByPolicyIdError,
    Options<PatchAdminManagedDomainPoliciesByPolicyIdData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await patchAdminManagedDomainPoliciesByPolicyId({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const getAdminUsersQueryKey = (options?: Options<GetAdminUsersData>) =>
  createQueryKey("getAdminUsers", options)

/**
 * Find a user across every organization
 */
export const getAdminUsersOptions = (options?: Options<GetAdminUsersData>) =>
  queryOptions<
    GetAdminUsersResponse,
    DefaultError,
    GetAdminUsersResponse,
    ReturnType<typeof getAdminUsersQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAdminUsers({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getAdminUsersQueryKey(options),
  })

const createInfiniteParams = <
  K extends Pick<QueryKey<Options>[0], "body" | "headers" | "path" | "query">,
>(
  queryKey: QueryKey<Options>,
  page: K,
) => {
  const params = { ...queryKey[0] }
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const getAdminUsersInfiniteQueryKey = (
  options?: Options<GetAdminUsersData>,
): QueryKey<Options<GetAdminUsersData>> => createQueryKey("getAdminUsers", options, true)

/**
 * Find a user across every organization
 */
export const getAdminUsersInfiniteOptions = (options?: Options<GetAdminUsersData>) => {
  const opts = infiniteQueryOptions<
    GetAdminUsersResponse,
    DefaultError,
    InfiniteData<GetAdminUsersResponse>,
    QueryKey<Options<GetAdminUsersData>>,
    string | Pick<QueryKey<Options<GetAdminUsersData>>[0], "body" | "headers" | "path" | "query">
  >(
    // @ts-ignore
    {
      queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<
          QueryKey<Options<GetAdminUsersData>>[0],
          "body" | "headers" | "path" | "query"
        > =
          typeof pageParam === "object"
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const { data } = await getAdminUsers({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: getAdminUsersInfiniteQueryKey(options),
    },
  )
  return opts as Omit<typeof opts, "initialData">
}

/**
 * Sign in as a user, for support. Recorded against both people.
 */
export const postAdminUsersImpersonateMutation = (
  options?: Partial<Options<PostAdminUsersImpersonateData>>,
): UseMutationOptions<
  PostAdminUsersImpersonateResponse,
  PostAdminUsersImpersonateError,
  Options<PostAdminUsersImpersonateData>
> => {
  const mutationOptions: UseMutationOptions<
    PostAdminUsersImpersonateResponse,
    PostAdminUsersImpersonateError,
    Options<PostAdminUsersImpersonateData>
  > = {
    mutationFn: async (fnOptions) => {
      const { data } = await postAdminUsersImpersonate({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}
