// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions } from "@tanstack/react-query"

import { client } from "../client.gen"
import { getAdminUserTest, type Options } from "../sdk.gen"
import type { GetAdminUserTestData, GetAdminUserTestResponse } from "../types.gen"

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, "baseUrl" | "body" | "headers" | "path" | "query"> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>,
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const getAdminUserTestQueryKey = (options?: Options<GetAdminUserTestData>) =>
  createQueryKey("getAdminUserTest", options)

/**
 * Get messages for a company job posting chat
 */
export const getAdminUserTestOptions = (options?: Options<GetAdminUserTestData>) =>
  queryOptions<
    GetAdminUserTestResponse,
    DefaultError,
    GetAdminUserTestResponse,
    ReturnType<typeof getAdminUserTestQueryKey>
  >({
    queryFn: async ({ queryKey, signal }) => {
      const { data } = await getAdminUserTest({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getAdminUserTestQueryKey(options),
  })
