import { open, seal } from "@lib/envelope"
import type { DB } from "@sproutos/db"
import { type Kysely, sql } from "kysely"
import { Client } from "pg"
import { v7 } from "uuid"
import { assertSafeIdentifier, databaseNameFor, postgresUri, roleNameFor } from "./naming"
import {
  type ConnectionDetails,
  type ProvisionInput,
  type ProvisionResult,
  ServiceNotProvisionedError,
  type ServiceDriver,
} from "./types"

/**
 * A Postgres service on a cluster we run.
 *
 * `database_instance.provider` allows `neon | byo | sprout`; this is `sprout` — a database and a
 * role on an ordinary Postgres server. Self-hosted Neon (branching, scale-to-zero, TASK 30) is a
 * separate provider on the same interface, and it needs a pageserver and safekeepers that do not
 * exist yet. This one works today, which makes it the honest starting point rather than a stub
 * pretending to be branching storage.
 *
 * **Provisioning is DDL, and DDL cannot be parameterized.** Every identifier that reaches a
 * statement here is derived from a UUID and asserted before use; nothing a customer typed gets
 * near it.
 */

export type SproutPostgresConfig = {
  /** Where customer databases live. The superuser connection — never handed to a customer. */
  adminUrl: string
  /** What goes in the customer's URI, which may differ from adminUrl behind a proxy. */
  publicHost: string
  publicPort: number
  sslmode?: string
}

export function sproutPostgresConfigFromEnv(
  env: NodeJS.ProcessEnv = process.env,
): SproutPostgresConfig {
  const adminUrl = env.SERVICE_POSTGRES_ADMIN_URL ?? env.DATABASE_URL
  if (adminUrl === undefined || adminUrl === "") {
    throw new Error("SERVICE_POSTGRES_ADMIN_URL is not set")
  }

  const parsed = new URL(adminUrl)
  return {
    adminUrl,
    publicHost: env.SERVICE_POSTGRES_PUBLIC_HOST ?? parsed.hostname,
    publicPort: Number(env.SERVICE_POSTGRES_PUBLIC_PORT ?? parsed.port ?? 5432),
    ...(env.SERVICE_POSTGRES_SSLMODE === undefined
      ? {}
      : { sslmode: env.SERVICE_POSTGRES_SSLMODE }),
  }
}

/** 32 bytes of base64url. Long enough that it is never the weak part of the URI. */
function generatePassword(): string {
  return Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString("base64url")
}

/**
 * Binds a password's ciphertext to the role row that holds it.
 *
 * KMS authenticates the context, so a blob copied onto another role's row does not decrypt. Shared
 * by seal and open for the reason `@lib/agent` learned the hard way: a one-word difference between
 * writer and reader stores fine and never opens.
 */
export function rolePasswordContext(databaseRoleId: string): Record<string, string> {
  return { field: "database_role.password", databaseRoleId }
}

async function withAdmin<T>(
  config: SproutPostgresConfig,
  body: (client: Client) => Promise<T>,
): Promise<T> {
  const client = new Client({ connectionString: config.adminUrl })
  await client.connect()
  try {
    return await body(client)
  } finally {
    await client.end()
  }
}

export function sproutPostgresDriver(db: Kysely<DB>, config: SproutPostgresConfig): ServiceDriver {
  async function locate(backendServiceId: string) {
    const row = await db
      .selectFrom("databaseInstance")
      .innerJoin("databaseBranch", "databaseBranch.databaseInstanceId", "databaseInstance.id")
      .innerJoin("databaseRole", "databaseRole.databaseBranchId", "databaseBranch.id")
      .select([
        "databaseInstance.id as instanceId",
        "databaseBranch.id as branchId",
        "databaseRole.id as roleId",
        "databaseRole.roleName as roleName",
        "databaseRole.passwordCiphertext as ciphertext",
        "databaseRole.passwordWrappedDek as wrappedDek",
        "databaseRole.passwordKmsKeyId as kmsKeyId",
      ])
      .where("databaseInstance.backendServiceId", "=", backendServiceId)
      .where("databaseInstance.deletedAt", "is", null)
      .where("databaseBranch.kind", "=", "primary")
      .executeTakeFirst()

    if (row === undefined) throw new ServiceNotProvisionedError(backendServiceId)
    return row
  }

  function detailsFor(backendServiceId: string, roleName: string): ConnectionDetails {
    return {
      host: config.publicHost,
      port: config.publicPort,
      database: databaseNameFor(backendServiceId),
      username: roleName,
    }
  }

  async function provision(input: ProvisionInput): Promise<ProvisionResult> {
    const database = databaseNameFor(input.backendServiceId)
    const role = roleNameFor(input.backendServiceId)
    assertSafeIdentifier(database)
    assertSafeIdentifier(role)

    const password = generatePassword()

    await withAdmin(config, async (client) => {
      // The password is a parameter of the *statement text* here because Postgres has no bind
      // parameters in DDL. It is generated by us and base64url, so it contains nothing that can
      // close the quote — but the literal is still escaped rather than trusted.
      await client.query(`create role ${role} login password ${quoteLiteral(password)}`)
      // `create database` cannot run inside a transaction block, which is why this is a sequence
      // of statements rather than one atomic unit. A failure between them leaves an orphaned role,
      // which `destroy` cleans up because it drops both regardless of what exists.
      await client.query(`create database ${database} owner ${role}`)
      // Revoke the implicit grant every role gets on a new database's public schema, so one
      // customer's role cannot connect to another customer's database.
      await client.query(`revoke all on database ${database} from public`)
      await client.query(`grant all privileges on database ${database} to ${role}`)
    })

    const roleId = v7()
    const sealed = await seal(password, rolePasswordContext(roleId))

    await db.transaction().execute(async (tx) => {
      const instanceId = v7()
      const branchId = v7()

      await tx
        .insertInto("databaseInstance")
        .values({
          id: instanceId,
          backendServiceId: input.backendServiceId,
          projectId: input.projectId,
          provider: "sprout",
          region: null,
          status: "active",
        })
        .execute()

      await tx
        .insertInto("databaseBranch")
        .values({
          id: branchId,
          databaseInstanceId: instanceId,
          name: "main",
          kind: "primary",
          host: config.publicHost,
          isProtected: true,
        })
        .execute()

      await tx
        .insertInto("databaseRole")
        .values({
          id: roleId,
          databaseBranchId: branchId,
          roleName: role,
          passwordCiphertext: sealed.ciphertext,
          passwordWrappedDek: sealed.wrappedDek,
          passwordKmsKeyId: sealed.kmsKeyId,
        })
        .execute()
    })

    return {
      ...detailsFor(input.backendServiceId, role),
      connectionUri: postgresUri({
        ...detailsFor(input.backendServiceId, role),
        password,
        ...(config.sslmode === undefined ? {} : { sslmode: config.sslmode }),
      }),
    }
  }

  async function connectionUri(backendServiceId: string): Promise<string> {
    const row = await locate(backendServiceId)
    const password = await open(
      { ciphertext: row.ciphertext, wrappedDek: row.wrappedDek, kmsKeyId: row.kmsKeyId },
      rolePasswordContext(row.roleId),
    )

    // Stamped so "when was this last revealed" is answerable. The audit row is written by the
    // route; this is the cheap denormalized answer a list page can show.
    await db
      .updateTable("databaseRole")
      .set({ revealedAt: new Date() })
      .where("id", "=", row.roleId)
      .execute()

    return postgresUri({
      ...detailsFor(backendServiceId, row.roleName),
      password,
      ...(config.sslmode === undefined ? {} : { sslmode: config.sslmode }),
    })
  }

  async function details(backendServiceId: string): Promise<ConnectionDetails> {
    const row = await locate(backendServiceId)
    return detailsFor(backendServiceId, row.roleName)
  }

  async function rotateCredentials(backendServiceId: string): Promise<string> {
    const row = await locate(backendServiceId)
    assertSafeIdentifier(row.roleName)
    const password = generatePassword()

    await withAdmin(config, async (client) => {
      await client.query(`alter role ${row.roleName} password ${quoteLiteral(password)}`)
    })

    const sealed = await seal(password, rolePasswordContext(row.roleId))
    await db
      .updateTable("databaseRole")
      .set({
        passwordCiphertext: sealed.ciphertext,
        passwordWrappedDek: sealed.wrappedDek,
        passwordKmsKeyId: sealed.kmsKeyId,
        rotatedAt: new Date(),
      })
      .where("id", "=", row.roleId)
      .execute()

    return postgresUri({
      ...detailsFor(backendServiceId, row.roleName),
      password,
      ...(config.sslmode === undefined ? {} : { sslmode: config.sslmode }),
    })
  }

  async function suspend(backendServiceId: string): Promise<void> {
    const row = await locate(backendServiceId)
    assertSafeIdentifier(row.roleName)

    // `nologin` rather than terminating the database: existing data is untouched and resuming is
    // one statement. A suspended service that lost its data would not be a suspension.
    await withAdmin(config, async (client) => {
      await client.query(`alter role ${row.roleName} nologin`)
    })

    await db
      .updateTable("databaseInstance")
      .set({ status: "suspended", updatedAt: new Date() })
      .where("id", "=", row.instanceId)
      .execute()
  }

  async function destroy(backendServiceId: string): Promise<void> {
    const database = databaseNameFor(backendServiceId)
    const role = roleNameFor(backendServiceId)
    assertSafeIdentifier(database)
    assertSafeIdentifier(role)

    await withAdmin(config, async (client) => {
      // `with (force)` disconnects sessions still on it; without it a single idle client keeps a
      // customer's deleted database alive forever.
      await client.query(`drop database if exists ${database} with (force)`)
      await client.query(`drop role if exists ${role}`)
    })

    await db
      .updateTable("databaseInstance")
      .set({ status: "deleting", deletedAt: new Date(), updatedAt: new Date() })
      .where("backendServiceId", "=", backendServiceId)
      .execute()
  }

  return {
    kind: "postgres",
    connectionUri,
    destroy,
    details,
    provision,
    rotateCredentials,
    suspend,
  }
}

/** Postgres string literal quoting: double the single quotes, and nothing else is special. */
function quoteLiteral(value: string): string {
  return `'${value.replaceAll("'", "''")}'`
}

export { sql }
